ZB_MART/CoreApp/urls.py
from django.urls import path
from django.contrib import admin,auth
from django.conf import settings
from CoreApp import views
from .views import HomeView,ShopView,CategoryView,Cartview,add_to_cart,remove_from_cart,remove_single_item_from_cart
from django.contrib.auth import views as auth_views

app_name = 'CoreApp'

urlpatterns = [path('',HomeView.as_view(),name='home'),
               path('shop/', ShopView.as_view(), name='shop'),
               path('category/<slug>/', CategoryView.as_view(), name='category'),
               path('cart/', Cartview.as_view(), name='cart'),
                path('signup/', views.SignUp.as_view(), name='signup'),
                path('login/', auth_views.LoginView.as_view(), name='login'),
                path('logout/', auth_views.LogoutView.as_view(), name='logout'),
                path('add-to-cart/<slug>/', add_to_cart, name='add-to-cart'),
                path('remove-item-from-cart/<slug>/', remove_single_item_from_cart,name='remove-single-item-from-cart'),
                path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
               ]

ZB_MART/ZB_MART/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('CoreApp.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

ZB_MART/CoreApp/models.py
from django.conf import settings
from django.db import models
from django.db.models import Sum
from django.shortcuts import reverse



LABEL_CHOICES = (
    ('S', 'sale'),
    ('N', 'new'),
    ('P', 'promotion')
)



class Slide(models.Model):
    id_slide = models.IntegerField(primary_key=True)
    caption1 = models.CharField(max_length=100)
    caption2 = models.CharField(max_length=100)
    link = models.CharField(max_length=100)
    image = models.ImageField(help_text="Size: 1920x570")
    is_active = models.BooleanField(default=True)
    
    def __str__(self):
        return "{} - {}".format(self.caption1, self.caption2)

class Category(models.Model):
    id_category = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse("CoreApp:category", kwargs={
            'slug': self.slug
        })


class Item(models.Model):
    id_Item = models.IntegerField(primary_key=True)
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    stock_no = models.CharField(max_length=10)
    description_short = models.CharField(max_length=50)
    description_long = models.TextField()
    image = models.ImageField()
    is_active = models.BooleanField(default=True)

    def __str__(self):
        return self.title

class OrderItem(models.Model):
    id_orderItem = models.IntegerField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE,null=True)
    quantity = models.IntegerField(default=1)

    def __str__(self):
        return f"{self.quantity} of {self.item.title}"

    def get_total_item_price(self):
        return self.quantity * self.item.price

    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price

    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    



class Order(models.Model):
    id_order = models.IntegerField(primary_key=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()
    ordered = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        return total
    
    

ZB_MART/templates/base.html
<!DOCTYPE html>
<html lang="en">
  {% include "header.html" %}

  <title>{% block head_title %}{% endblock %}</title>
  {% block extra_head %} {% endblock %}
  <style type="text/css">
    .form-control {
    display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
}
  </style>
  <body class="animsition">
    {% include "nav.html"%}
    <div class="mt-2">
      {% if messages %} {% for message in messages %}
      <div
        class="alert alert-{{ message.tags }} alert-dismissible fade show"
        role="alert"
      >
        {{ message }}

        <button
          type="button"
          class="close"
          data-dismiss="alert"
          aria-label="Close"
        >
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    </div>

    {% endfor %} 
    {% endif %} 

    {% block content %} 
    {% endblock content %}

     {% block extra_body %} 
     {% endblock %} 

    {% include "footer.html"%} 
    {% include "script.html"%}

    {% block extra_scripts %}
    {% endblock extra_scripts %}
  </body>
</html>

ZB_MART/templates/cart.html
{% extends 'base.html' %}
{% load static %}
{% block content %}

<section class="bg-title-page p-t-40 p-b-50 flex-col-c-m"
	style="background-image: url('{% static 'images/heading-pages-01.jpg' %}'); color: black;">
	<h2 class="l-text2 t-center">
		Cart
	</h2>
</section>

{% if user.is_authenticated %}
<div class="container">
	<div class="row">
		<div class="col-lg-12">
			<table class="table">
				<thead>
					<tr>
						<th scope="col">#</th>
						<th scope="col"></th>
						<th scope="col">Product Name</th>
						<th scope="col">Price</th>
						<th scope="col" class="pl-4">Qty</th>
						<th scope="col">Total Price</th>
					</tr>
				</thead>
				<tbody>
					{% for order_item in object.items.all %}
					<tr>
						<th scope="row">{{ forloop.counter }}</th>
						<td>
							<img src="{{ order_item.item.image.url }}" style="width: 130px;">
						</td>
						<td>{{ order_item.item.title }}</td>
						<td>{{ order_item.item.price }}</td>
						<td>
							<a href="{% url 'CoreApp:remove-single-item-from-cart' order_item.item.slug %}"><i
									class="fas fa-minus mr-3"></i></a>
							{{ order_item.quantity }}
							<a href="{% url 'CoreApp:add-to-cart' order_item.item.slug %}"><i
									class="fas fa-plus ml-3"></i></a>
						</td>
						<td>
							{% if order_item.item.discount_price %}
							${{ order_item.get_total_discount_item_price}}
							<span class="badge badge-primary"> Saving ${{ order_item.get_amount_saved }}</span>
							{% else %}
							${{ order_item.get_total_item_price}}
							{% endif %}
							<a style="color: red" href="{% url 'CoreApp:remove-from-cart' order_item.item.slug %}">
								<i class="fas fa-trash float-right"></i>
							</a>
						</td>
					</tr>
					{% empty %}
					<tr>
						<td colspan="5">Your cart is empty</td>
					</tr>
				</tbody>
				{% endfor %}
				{% if object.get_total %}
				<tr>
					<td colspan="5"><b>Order Total : </b></td>
					<td><b>${{ object.get_total }}</b></td>
				</tr>
				<tr>
					<td colspan="5">
						<a href="{% url 'CoreApp:cart' %}" class="btn btn-warning float-right ml-2">Checkout</a>
						<a href="{% url 'CoreApp:shop' %}" class="btn btn-primary float-right">Continue Shopping</a>
					</td>
				</tr>
				{% endif %}
			</table>
		</div>
	</div>
</div>
{% else %}
ok
{% endif %}

{% endblock content %}

ZB_MART/templates/category.html
{% extends 'base.html' %}
{% load static %}
{% load category_template_tags %}
{% block content %}
<style type="text/css">
	.selection-2{
	display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
	}
</style>

	<!-- Title Page -->
	<section class="bg-title-page p-t-50 p-b-40 flex-col-c-m" style="background-image: url(/media/{{ category_image }});">
		<h2 class="l-text2 t-center">
			{{ category_title }}
		</h2>
		<p class="m-text13 t-center">
			{{ category_description }}
		</p>
	</section>


	<!-- Content page -->
	<section class="bgwhite p-t-55 p-b-65">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
					<div class="leftbar p-r-20 p-r-0-sm">
						<!--  -->
						<h4 class="m-text14 p-b-7">
							Categories
						</h4>

						<ul class="p-b-54">
							<li class="p-t-4">
								<a href="{% url 'CoreApp:shop' %}" class="s-text13 active1">
									All
								</a>
							</li>

							{% categories_li_a %}

						</ul>

					</div>
				</div>

				<div class="col-sm-6 col-md-8 col-lg-9 p-b-50">
					<!--  -->
					<div class="flex-sb-m flex-w p-b-35">
						<span class="s-text8 p-t-5 p-b-5">
							Showing results
						</span>
					</div>

					<!-- Product --> 	
					<div class="row">
						{% for item in object_list %}
						<div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
							<!-- Block2 -->
							<div class="block2">
								<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
									<img src="{{ item.image.url }}" alt="IMG-PRODUCT" 
								style="height: 360px;">

									<div class="block2-overlay trans-0-4">
										<a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
											<i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
											<i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
										</a>

										<div class="block2-btn-addcart w-size1 trans-0-4">
											<!-- Button -->
											<a href="{% url 'CoreApp:add-to-cart' item.slug %}">
												<button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
													Add to Cart
												</button>
											</a>
										</div>
									</div>
								</div>

								<div class="block2-txt p-t-20">
									<a href="{{item.get_absolute_url}}" class="block2-name dis-block s-text3 p-b-5">
										{{item.title}}
									</a>

									<span class="block2-price m-text6 p-r-5">
										${{item.price}}
									</span>
								</div>
							</div>
						</div>
						{% endfor %}

						

						
				
				</div>
				<!-- ---- row end ------- -->

				<br>
				<!-- Pagination -->
				{% if is_paginated %}
				<div class="pagination flex-m flex-w p-t-26">
					{% if page_obj.has_previous %}
					<a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
						<span class="sr-only">Previous</span>
					</a>
					{% endif %}
					<a href="?page={{ page_obj.number }}" class="item-pagination flex-c-m trans-0-4 active-pagination">{{page_obj.number}}</a>
					
					
					{% if page_obj.has_next %}
					<a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
							<span class="sr-only">Next</span>
						</a>
						{% endif %}
				</div>
				{% endif %}
			</div>
		</div>
	</section>


		{% endblock content %}

ZB_MART/templates/index.html
{% extends 'base.html' %}
{% load static %}
{% load category_template_tags %}
{% load slide_template_tags %}
{% block content %}
<style>
	/*[ Block2 ]
///////////////////////////////////////////////////////////
*/
.block2-labelpromotion::before,
.block2-labelsale::before,
.block2-labelnew::before 
{
  z-index: 100;
  font-family: Montserrat-Regular;
  font-size: 12px;
  color: white;
  display: -webkit-box;
  display: -webkit-flex;
  display: -moz-box;
  display: -ms-flexbox;
  display: flex;
  justify-content: center;
  align-items: center;
  width: 50px;
  height: 22px;
  border-radius: 11px;
  position: absolute;
  top: 12px;
  left: 12px;
}

.block2-labelsale::before {
  background-color: white;
  color: #000;
  content: 'Sale';
}

.block2-labelnew::before {
  background-color: #007bff;
  content: 'New';
}

.block2-labelpromotion::before{
	background-color: #000;
	content: 'Promotion';
	width: 70px;
  }


  .btn-dark {
    color: #fff;
    background-color: #000;
    border-color: #000;
}

.btn-outline-dark {
    color: #000;
    border-color: #000;
}


</style>

	<!-- Slide1 -->
	<section class="slide1">
		<div class="wrap-slick1">
			<div class="slick1">
				{% slides %}
			</div>
		</div>
	</section>

	<!-- Category start -->
	<style>
		.hov1{
			background-color: white !important;
			color: black !important;
			
		}
	</style>
	<section class="banner bgwhite p-t-40 p-b-40">
		<div class="container">
			<div class="row">

				{% categories_div %}

			</div>
		</div>
	</section>

	<!-- New Product -->
	<style>
		.newproduct{
			margin-bottom: 2px;
			padding-bottom: 2px;
		}
	</style>
	<section class="newproduct bgwhite p-t-45 p-b-105">
		<div class="container">
			<div class="sec-title p-b-60">
				<h3 class="m-text5 t-center">
					Featured Products
				</h3>
			</div>

			<!-- Slide2 -->
			<div class="wrap-slick2">
				<div class="slick2">

				{% for item in object_list %}
					<div class="item-slick2 p-l-15 p-r-15">
						<!-- Block2 -->
						<div class="block2">
							
							<div class="block2-img wrap-pic-w of-hidden pos-relative block2-label{{item.get_label_display}}">
								<a href="{{item.get_absolute_url}}">
								<img src="{{ item.image.url }}" alt="IMG-PRODUCT" 
								style="height: 370px; width:100%; "></a>
							</div>
							

							<div class="block2-txt p-t-20">
								<a href="{{item.get_absolute_url}}" class="block2-name dis-block s-text3 p-b-5" style="color: black;">
									{{ item.title }}
								</a>

								{% if item.discount_price %}
								<span class="block2-oldprice m-text7 p-r-5" style="color: black;">
									${{ item.price }}
								</span>

								<span class="block2-newprice m-text8 p-r-5">
									${{ item.discount_price }}
								</span>
								{% else %}
								<span class="block2-price m-text6 p-r-5" style="color: black;">
									${{ item.price }}
								</span>
								{% endif %}
								
							</div>
						</div>
					</div>
				
					{% endfor %}

				</div>
			</div>

		</div>
	</section>

	<!-- ------------------Banner2  start ------------------------>
	<style>
		.banner2{
			background-color: #fff;
			margin-right: 1rem;
			margin-left: 1rem;
			margin-bottom: 0 !important;
			padding-bottom: 0 !important;
		}

		.ban_img{
			height: 680px;
			width: 100%;
		}
		.ban5_img{
			height: 580px;
			width: 100%;
		}

		.btn-light {
			color: #000;
			background-color: #fff;
			border-color: #fff;
			border-radius: 20px;
		}
		.wrap-btn-slide1 a:hover{
			background-color: whitesmoke;
			color: #000 !important;
			opacity: 0.7;
	
		}
	</style>
	
	<!-- ------------------Banner2  start ------------------------>

	<!-- ------------------Banner4  start ------------------------>
<!-- Slide1 -->

<style>
	.slide1 button:hover{
		background-color: white !important;
		color: black;
	}
</style>

	<!-- Shipping -->
	<section class="shipping bgwhite p-t-62 p-b-46">
		<div class="flex-w p-l-15 p-r-15">
			<div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
				<h4 class="m-text12 t-center">
					Free Delivery Worldwide
				</h4>

				<a href="#" class="s-text11 t-center">
					Click here for more info
				</a>
			</div>

			<div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 bo2 respon2">
				<h4 class="m-text12 t-center">
					30 Days Return
				</h4>

				<span class="s-text11 t-center">
					Simply return it within 30 days for an exchange.
				</span>
			</div>

			<div class="flex-col-c w-size5 p-l-15 p-r-15 p-t-16 p-b-15 respon1">
				<h4 class="m-text12 t-center">
					Store Opening
				</h4>

				<span class="s-text11 t-center">
					Shop open from Monday to Sunday
				</span>
			</div>
		</div>
	</section>

	{% endblock content %}


	

ZB_MART/templates/nav.html
{% load static %}
{% load cart_template_tags %}
{% load category_template_tags %}

<style>
	.topbar {
		background-color: white;
		color: black !important;
	}
	.topbar a:hover{
		color: black;
	}
</style>
<!-- Header -->
<header class="header1">
		<!-- Header desktop -->
		<div class="container-menu-header">
			<div class="topbar">
				<div class="topbar-social">
					<a href="#" class="topbar-social-item fab fa-facebook"></a>
					<a href="#" class="topbar-social-item fab fa-instagram"></a>
					<a href="#" class="topbar-social-item fab fa-pinterest-p"></a>
					<a href="#" class="topbar-social-item fab fa-twitter"></a>
					<a href="#" class="topbar-social-item fab fa-youtube"></a>
				</div>


				<div class="topbar-child2">
					<span class="topbar-email">
					{% if user.is_authenticated %}
						{{ user.username }}
					{% else %}
					No User
					{% endif %}
					</span>
				</div>
			</div>

			<div class="wrap_header">
				<!-- Logo -->
				<a href="{% url 'CoreApp:home' %}" class="logo">
					<p style="color: black; "><b style="font-size: 22px;">ZB</b>-Mart</p>
				</a>

				<!-- Menu -->
				<div class="wrap_menu">
					<nav class="menu">
						<ul class="main_menu">
							<li>
								<a href="{% url 'CoreApp:home' %}">Home</a>

							</li>

							<li>
								<a href="{% url 'CoreApp:shop' %}">Shop</a>
							</li>

							{% categories %}

						</ul>
					</nav>
				</div>
				
				
				<!-- Header Icon -->
				<div class="header-icons">
					<a href="{% url 'CoreApp:login' %}" class="header-wrapicon1 dis-block">
						<img src="{% static 'images/icons/icon-header-01.png' %}" class="header-icon1" alt="ICON">
					</a>

					<span class="linedivide1"></span>

					
					<div class="header-wrapicon2">
						<img src="{% static 'images/icons/icon-header-02.png' %}" class="header-icon1 js-show-header-dropdown" alt="ICON">
						{% if user.is_authenticated %}
						<span class="header-icons-noti">{{ request.user|cart_item_count }}</span>
						
						<div class="header-cart header-dropdown">
							<ul class="header-cart-wrapitem">
									{% for order_item in object.items.all %}
									<li class="header-cart-item">
										<div class="header-cart-item-img">
											<img src="{{ order_item.item.image.url }}" alt="IMG">
										</div>
									
										<div class="header-cart-item-txt">
											<a href="#" class="header-cart-item-name">
												{{ order_item.item.title }}
											</a>
									
											<span class="header-cart-item-info">
												{{ order_item.quantity }} x ${{ order_item.item.price }}
											</span>
										</div>
									</li>
									{% endfor %}
							</ul>

							<div class="header-cart-total">
								Total: ${{ object.get_total }}
							</div>

							<div class="header-cart-buttons">
								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="{% url 'CoreApp:cart' %}" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										View Cart
									</a>
								</div>

								<div class="header-cart-wrapbtn">
									<!-- Button -->
									<a href="#" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
										Check Out
									</a>
								</div>
							</div>
						</div>
					</div>
					{% else %}
					<div class="header-cart header-dropdown">
						<a href="{% url 'CoreApp:login' %}" class="flex-c-m size1 bg1 bo-rad-20 hov1 s-text1 trans-0-4">
						Login
						</a></div>
					{% endif %}
				</div>
			</div>
		</div>

		<!-- Menu Mobile -->
		<div class="wrap-side-menu" >
			<nav class="side-menu">
				<ul class="main-menu">

					<li class="item-topbar-mobile p-l-20 p-t-8 p-b-8">
						<div class="topbar-child2-mobile">
							<span class="topbar-email">
								fashe@example.com
							</span>

							<div class="topbar-language rs1-select2">
								<select class="selection-1" name="time">
									<option>USD</option>
									<option>EUR</option>
								</select>
							</div>
						</div>
					</li>

					<li class="item-topbar-mobile p-l-10">
						<div class="topbar-social-mobile">
							<a href="#" class="topbar-social-item fa fa-facebook"></a>
							<a href="#" class="topbar-social-item fa fa-instagram"></a>
							<a href="#" class="topbar-social-item fa fa-pinterest-p"></a>
							<a href="#" class="topbar-social-item fa fa-snapchat-ghost"></a>
							<a href="#" class="topbar-social-item fa fa-youtube-play"></a>
						</div>
					</li>

					<li class="item-menu-mobile">
						<a href="{% url 'CoreApp:home' %}">Home</a>
					</li>

					<li class="item-menu-mobile">
						<a href="{% url 'CoreApp:shop' %}">Shop</a>
					</li>

					{% categories_mobile %}

				</ul>
			</nav>
		</div>
	</header>

ZB_MART/templates/shop.html
{% extends 'base.html' %}

{% load category_template_tags %}
{% block content %}
<style type="text/css">
	.selection-2{
	display: block;
    width: 100%;
    height: calc(1.5em + .75rem + 2px);
    padding: .375rem .75rem;
    font-size: 1rem;
    font-weight: 400;
    line-height: 1.5;
    color: #495057;
    background-color: #fff;
    background-clip: padding-box;
    border: 1px solid #ced4da !important;
    border-radius: .25rem;
    transition: border-color .15s ease-in-out,box-shadow .15s ease-in-out;
	}
</style>

	<!-- Title Page -->
	<section class="bg-title-page p-t-50 p-b-40 flex-col-c-m" style="background-image: url(/static/images/heading-pages-02.jpg)	;">
		<h2 class="l-text2 t-center">
			Shop
		</h2>
		<p class="m-text13 t-center">
			All categories
		</p>
	</section>


	<!-- Content page -->
	<section class="bgwhite p-t-55 p-b-65">
		<div class="container">
			<div class="row">
				<div class="col-sm-6 col-md-4 col-lg-3 p-b-50">
					<div class="leftbar p-r-20 p-r-0-sm">
						<!--  -->
						<h4 class="m-text14 p-b-7">
							Categories
						</h4>

						<ul class="p-b-54">
							<li class="p-t-4">
								<a href="/shop" class="s-text13 active1">
									All
								</a>
							</li>

							{% categories_li_a %}

						</ul>
					</div>
				</div>

				<div class="col-sm-6 col-md-8 col-lg-9 p-b-50">
					<!--  -->
					<div class="flex-sb-m flex-w p-b-35">
						<span class="s-text8 p-t-5 p-b-5">
							Showing 	results
						</span>
					</div>

					<!-- Product -->
					<div class="row">
						{% for item in object_list %}
						<div class="col-sm-12 col-md-6 col-lg-4 p-b-50">
							<!-- Block2 -->
							<div class="block2">
								<div class="block2-img wrap-pic-w of-hidden pos-relative block2-labelnew">
									<img src="{{ item.image.url }}" alt="IMG-PRODUCT" 
								style="height: 360px;">

									<div class="block2-overlay trans-0-4">
										<a href="#" class="block2-btn-addwishlist hov-pointer trans-0-4">
											<i class="icon-wishlist icon_heart_alt" aria-hidden="true"></i>
											<i class="icon-wishlist icon_heart dis-none" aria-hidden="true"></i>
										</a>

										<div class="block2-btn-addcart w-size1 trans-0-4">
											<!-- Button -->
											<a href="{% url 'CoreApp:add-to-cart' item.slug %}">
											<button class="flex-c-m size1 bg4 bo-rad-23 hov1 s-text1 trans-0-4">
												Add to Cart
											</button>
											</a>
										</div>
									</div>
								</div>

								<div class="block2-txt p-t-20">
									<a href="{{item.get_absolute_url}}" class="block2-name dis-block s-text3 p-b-5">
										{{item.title}}
									</a>

									<span class="block2-price m-text6 p-r-5">
										${{item.price}}
									</span>
								</div>
							</div>
						</div>
						{% endfor %}

						

								
				</div>
				<!-- ---- row end ------- -->

				<br>
				<!-- Pagination -->
				{% if is_paginated %}
				<div class="pagination flex-m flex-w p-t-26">
					{% if page_obj.has_previous %}
					<a class="page-link" href="?page={{ page_obj.previous_page_number}}" aria-label="Previous">
						<span aria-hidden="true">&laquo;</span>
						<span class="sr-only">Previous</span>
					</a>
					{% endif %}
					<a href="?page={{ page_obj.number }}" class="item-pagination flex-c-m trans-0-4 active-pagination">{{page_obj.number}}</a>
					
					
					{% if page_obj.has_next %}
					<a class="page-link" href="?page={{ page_obj.next_page_number}}" aria-label="Next">
							<span aria-hidden="true">&raquo;</span>
							<span class="sr-only">Next</span>
						</a>
						{% endif %}
				</div>
				{% endif %}
			</div>
		</div>
	</section>


		{% endblock content %}